---
- hosts: all
  vars:
    user:
      - "user1"
  tasks:
    - name: "Create user accounts"
      user:
        name: "{{ item }}"
      with_items: "{{ user }}"
    - name: "Add authorized keys"
      authorized_key:
        user: "{{ item }}"
        key: "{{ lookup('file', '/home/user1/.ssh/id_rsa.pub') }}"
      with_items: "{{ user }}"
