---
- name: Add new user with SSH key authentication
  user:
    name: "{{ username }}"
    state: present
    createhome: yes
    shell: /bin/bash

- name: Ensure SSH directory exists for the new user
  file:
    path: "/home/{{ username }}/.ssh"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0700'

- name: Add SSH key for the new user
  authorized_key:
    user: "{{ username }}"
    key: "{{ lookup('file', '/path/to/your/public_key.pub') }}"
    state: present
