version: '3'

services:
  php:
    build: .
    healthcheck:
      test: ["CMD", "curl", "-f", "http://nginx/"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ./www/index.php:/var/www/index.php
    depends_on:
      - php

volumes:
  php:
